// GENERATED by scripts/extract-content.mjs — do not edit by hand.

export interface PageHead {
  title: string;
  description: string;
  keywords: string | null;
  canonical: string;
  /** Page-level robots override (e.g. local-transport is noindexed). */
  robots: string | null;
  ogTitle: string | null;
  ogDescription: string | null;
  ogUrl: string | null;
  ogImage: string | null;
  twitterTitle: string | null;
  twitterDescription: string | null;
  twitterImage: string | null;
  /** Raw JSON-LD blocks, byte-for-byte from the legacy <head>. */
  jsonLd: string[];
}

export interface Crumb { label: string; href: string | null }

export interface LandingPage {
  slug: string;
  head: PageHead;
  hero: {
    breadcrumbs: Crumb[];
    overline: string;
    h1: string;
    lead: string | null;
    media: { html: string; style: string | null };
    actions: { label: string; href: string }[];
  };
  proseHtml: string;
  proseStyle: string | null;
  faq: { heading: string; items: { q: string; a: string }[] };
  related: { overline: string; heading: string; cards: { href: string; title: string }[] };
  cta: { heading: string; text: string };
}
